### ISSUE TITLE
What is the License?

### ISSUE THREAD

**Issue by leocaseiro** [sightread/sightread#117]
Hi, I was wondering what is the license for the sightread?
The description says it's open-source, but the package.json has a `private: true`.

**Comment by leocaseiro** [comment]
Just for context, I wanted to add the license here https://alternativeto.net/software/sightread/about/

**Comment by samouri** [comment]
GPL! Can't believe I never added one explicitly, my bad. Thank you for bringing this up. I'll add it now

**Comment by samouri** [comment]
Implemented in https://github.com/sightread/sightread/pull/118
