### ISSUE TITLE
Cannot read properties of undefined (reading 'left') on too low/high keys

### ISSUE THREAD

**Issue by j4k0xb** [sightread/sightread#122]
many pianos have a function to transpose +-12 but sightread crashes when rendering a midi note from outside the normal range:

![sightread](https://github.com/sightread/sightread/assets/55899582/60af8359-447c-4c49-81cc-96629f81b855)
seems to happen because it tries to access a non-existent lane.
https://github.com/sightread/sightread/blob/55089cb14ba4243b7e0b5759b21bb73811010e22/src/features/SongVisualization/falling-notes.ts#L231-L233

**Comment by samouri** [comment]
Thank you for the bug report! As a quick band-aid fix we should be able to ignore notes outside of the visible range. It'd also make sense to eventually expand the range s.t. it can view those notes as well.

**Comment by j4k0xb** [comment]
Alright I can make a PR to ignore them for now
