### ISSUE TITLE
App broken on Firefox 

### ISSUE THREAD

**Issue by andreaemonti** [sightread/sightread#152]
It used to work normally until a couple of weeks ago.

Now when I open the webapp (both in free play mode, or opening a song) as soon as a note is played (either by me, by clicking, or by the falling notes) that note is played repeatedly as fast as my computer can handle, producing a very bad sound and freezing/slowing down the app, until I close the tab.

**System info**
Browser: Firefox 130.0.1
OS: EndeavourOS (arch linux based)

**Comment by GunGunGun** [comment]
It could be because you enabled MIDI Controller.

**Comment by andreaemonti** [comment]
Thank you! Playing around with the switches I managed to solve.
