### ISSUE TITLE
Error when trying to upload local midi file

### ISSUE THREAD

**Issue by Finaff** [sightread/sightread#86]
Error message shown is : 

Unexpected chunk, expected MTrk, got Sequ

**Comment by samouri** [comment]
Can you share the midi file?

**Comment by Finaff** [comment]
Here's a link to the midi file: https://file.io/2BPUHMMP2iEf

It's really short (can it be a problem?). But I've tested it with synthesia and it is working.

**Comment by Finaff** [comment]
Oh. never mind, it seems that my file was the problem (not sure why). I opened it in a midi editor and re-saved it and now it is working. Thanks for the great app by the way.
